---
AllCops:
  Include:
    - Rakefile
    - rakelib/**
  Exclude:
    - vendor/**/*
Documentation:
  Enabled: false
EmptyLinesAroundBody:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 25
